In [1]:
import pandas as pd
import numpy as np

In [2]:
energy=pd.read_csv('Energy.csv')

In [3]:
energy

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,-25.013,-10.847,NaN,NaN,NaN,NaN,-0.789,...,0.579,NaN,2.503057e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17428,ZWE,Zimbabwe,2016,-37.694,-12.257,NaN,NaN,NaN,NaN,-14.633,...,0.641,NaN,2.515176e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17429,ZWE,Zimbabwe,2017,8.375,1.697,NaN,NaN,NaN,NaN,NaN,...,0.773,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17430,ZWE,Zimbabwe,2018,22.555,4.952,NaN,NaN,NaN,NaN,NaN,...,0.970,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17431,ZWE,Zimbabwe,2019,-35.015,-9.422,NaN,NaN,NaN,NaN,NaN,...,0.956,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [6]:
for col in energy.columns:
    print(col)

iso_code
country
year
coal_prod_change_pct
coal_prod_change_twh
gas_prod_change_pct
gas_prod_change_twh
oil_prod_change_pct
oil_prod_change_twh
energy_cons_change_pct
energy_cons_change_twh
biofuel_share_elec
biofuel_elec_per_capita
biofuel_cons_change_pct
biofuel_share_energy
biofuel_cons_change_twh
biofuel_consumption
biofuel_cons_per_capita
carbon_intensity_elec
coal_share_elec
coal_cons_change_pct
coal_share_energy
coal_cons_change_twh
coal_consumption
coal_elec_per_capita
coal_cons_per_capita
coal_production
coal_prod_per_capita
electricity_generation
biofuel_electricity
coal_electricity
fossil_electricity
gas_electricity
hydro_electricity
nuclear_electricity
oil_electricity
other_renewable_electricity
other_renewable_exc_biofuel_electricity
renewables_electricity
solar_electricity
wind_electricity
energy_per_gdp
energy_per_capita
fossil_cons_change_pct
fossil_share_energy
fossil_cons_change_twh
fossil_fuel_consumption
fossil_energy_per_capita
fossil_cons_per_capita
fossil_share_elec
gas_share_elec
gas_cons_change_pct
gas_share_energy
gas_cons_change_twh
gas_consumption
gas_elec_per_capita
gas_energy_per_capita
gas_production
gas_prod_per_capita
hydro_share_elec
hydro_cons_change_pct
hydro_share_energy
hydro_cons_change_twh
hydro_consumption
hydro_elec_per_capita
hydro_energy_per_capita
low_carbon_share_elec
low_carbon_electricity
low_carbon_elec_per_capita
low_carbon_cons_change_pct
low_carbon_share_energy
low_carbon_cons_change_twh
low_carbon_consumption
low_carbon_energy_per_capita
nuclear_share_elec
nuclear_cons_change_pct
nuclear_share_energy
nuclear_cons_change_twh
nuclear_consumption
nuclear_elec_per_capita
nuclear_energy_per_capita
oil_share_elec
oil_cons_change_pct
oil_share_energy
oil_cons_change_twh
oil_consumption
oil_elec_per_capita
oil_energy_per_capita
oil_production
oil_prod_per_capita
other_renewables_elec_per_capita
other_renewables_share_elec
other_renewables_cons_change_pct
other_renewables_share_energy
other_renewables_cons_change_twh
other_renewable_consumption
other_renewables_energy_per_capita
per_capita_electricity
population
primary_energy_consumption
renewables_elec_per_capita
renewables_share_elec
renewables_cons_change_pct
renewables_share_energy
renewables_cons_change_twh
renewables_consumption
renewables_energy_per_capita
solar_share_elec
solar_cons_change_pct
solar_share_energy
solar_cons_change_twh
solar_consumption
solar_elec_per_capita
solar_energy_per_capita
gdp
wind_share_elec
wind_cons_change_pct
wind_share_energy
wind_cons_change_twh
wind_consumption
wind_elec_per_capita
wind_energy_per_capita

In [9]:
#our focus countries
focus_countries = ['United States', 'India', 'Russia', 'United Kingdom', 'China']

In [10]:
#filter for focus countries
power_data = energy[energy["country"].isin(focus_countries)]
power_data

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
3345,CHN,China,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.360000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3346,CHN,China,1901,NaN,0.000,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3347,CHN,China,1902,NaN,0.291,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3348,CHN,China,1903,1972.001,5.731,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3349,CHN,China,1904,6.467,0.389,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16365,USA,United States,2016,-18.271,-912.933,-1.749,-129.471,-4.346,-286.140,-0.142,...,169.857,431.466,1.720000e+13,5.543,18.315,2.256,89.259,576.606,702.729,1785.069
16366,USA,United States,2017,6.534,266.804,2.587,188.146,5.818,366.362,0.340,...,237.712,600.286,NaN,6.266,11.372,2.504,65.573,642.179,782.265,1975.419
16367,USA,United States,2018,-1.676,-72.927,12.021,896.946,17.024,1134.436,3.544,...,285.435,716.584,NaN,6.486,6.588,2.577,42.305,684.484,833.547,2092.608
16368,USA,United States,2019,-7.130,-304.975,10.171,850.157,11.181,871.897,-0.998,...,324.842,815.400,NaN,7.086,9.652,2.855,66.063,750.547,896.194,2280.847
16369,USA,United States,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,400.693,NaN,NaN,8.310,NaN,NaN,NaN,NaN,1016.709,NaN

In [11]:
power_data = power_data[power_data["year"] >= 2000] #return data for only years greater than or equal to 2000
power_data

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
3445,CHN,China,2000,3.713,294.468,7.945,20.177,1.498,27.867,3.473,...,0.015,0.047,5.120000e+12,0.047,24.520,0.014,0.323,1.639,0.477,1.270
3446,CHN,China,2001,5.946,489.119,11.504,31.536,1.359,25.661,5.627,...,0.018,0.066,5.580000e+12,0.051,21.126,0.016,0.346,1.985,0.577,1.528
3447,CHN,China,2002,6.794,592.093,7.689,23.503,1.235,23.640,8.926,...,0.031,0.101,6.110000e+12,0.053,15.681,0.017,0.311,2.296,0.668,1.756
3448,CHN,China,2003,18.125,1686.982,7.207,23.725,1.629,31.571,16.441,...,0.048,0.133,6.570000e+12,0.056,18.296,0.017,0.420,2.716,0.790,2.065
3449,CHN,China,2004,17.095,1879.430,18.406,64.957,2.633,51.855,17.003,...,0.051,0.155,7.220000e+12,0.062,27.350,0.019,0.743,3.459,1.007,2.614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16365,USA,United States,2016,-18.271,-912.933,-1.749,-129.471,-4.346,-286.140,-0.142,...,169.857,431.466,1.720000e+13,5.543,18.315,2.256,89.259,576.606,702.729,1785.069
16366,USA,United States,2017,6.534,266.804,2.587,188.146,5.818,366.362,0.340,...,237.712,600.286,NaN,6.266,11.372,2.504,65.573,642.179,782.265,1975.419
16367,USA,United States,2018,-1.676,-72.927,12.021,896.946,17.024,1134.436,3.544,...,285.435,716.584,NaN,6.486,6.588,2.577,42.305,684.484,833.547,2092.608
16368,USA,United States,2019,-7.130,-304.975,10.171,850.157,11.181,871.897,-0.998,...,324.842,815.400,NaN,7.086,9.652,2.855,66.063,750.547,896.194,2280.847
16369,USA,United States,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,400.693,NaN,NaN,8.310,NaN,NaN,NaN,NaN,1016.709,NaN

In [12]:
#get column names with the word consumption in them
consumption_cols = [col for col in power_data.keys()[power_data.keys().str.contains('consumption')]]

In [13]:
consumption_cols

['biofuel_consumption',
 'coal_consumption',
 'fossil_fuel_consumption',
 'gas_consumption',
 'hydro_consumption',
 'low_carbon_consumption',
 'nuclear_consumption',
 'oil_consumption',
 'other_renewable_consumption',
 'primary_energy_consumption',
 'renewables_consumption',
 'solar_consumption',
 'wind_consumption']

In [16]:
power_data.keys().str.contains('consumption')

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False])

In [17]:
consumption_cols.append('country') #append country column
consumption_cols.append('year') #append year column
consumption_cols

['biofuel_consumption',
 'coal_consumption',
 'fossil_fuel_consumption',
 'gas_consumption',
 'hydro_consumption',
 'low_carbon_consumption',
 'nuclear_consumption',
 'oil_consumption',
 'other_renewable_consumption',
 'primary_energy_consumption',
 'renewables_consumption',
 'solar_consumption',
 'wind_consumption',
 'country',
 'year']

In [18]:
power_data = power_data[consumption_cols]
power_data

,biofuel_consumption,coal_consumption,fossil_fuel_consumption,gas_consumption,hydro_consumption,low_carbon_consumption,nuclear_consumption,oil_consumption,other_renewable_consumption,primary_energy_consumption,renewables_consumption,solar_consumption,wind_consumption,country,year
3445,0.000,8211.413,11119.510,246.958,617.806,673.045,46.492,2661.139,7.047,11792.554,626.553,0.061,1.639,China,2000
3446,0.053,8635.762,11633.089,276.458,765.635,823.025,48.218,2720.870,7.048,12456.115,774.807,0.086,1.985,China,2001
3447,0.444,9467.465,12699.612,294.136,789.596,868.346,68.897,2938.011,6.981,13567.957,799.449,0.132,2.296,China,2002
3448,1.618,11283.068,14896.342,341.748,772.847,902.343,118.079,3271.527,6.909,15798.685,784.264,0.174,2.716,China,2003
3449,5.556,13155.290,17375.205,399.840,957.047,1109.731,136.620,3820.075,6.843,18484.936,973.111,0.206,3.459,China,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16365,411.458,3960.744,21428.950,7490.995,663.312,4131.571,2132.795,9977.210,208.030,25560.520,1998.776,139.370,576.606,United States,2016
16366,411.034,3852.596,21331.723,7399.926,742.017,4315.665,2118.290,10079.202,207.001,25647.389,2197.375,195.144,642.179,United States,2017
16367,406.412,3689.462,22196.473,8199.426,719.554,4359.914,2111.488,10307.586,203.585,26556.388,2248.427,234.392,684.484,United States,2018
16368,406.191,3150.181,21891.102,8466.457,671.447,4400.254,2109.762,10274.464,193.987,26291.355,2290.491,268.320,750.547,United States,2019
16369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,2020

In [20]:
#group by country and sum the values in the remainig columns
total_power_consumed = power_data.groupby(['country']).sum()

In [21]:
total_power_consumed

,biofuel_consumption,coal_consumption,fossil_fuel_consumption,gas_consumption,hydro_consumption,low_carbon_consumption,nuclear_consumption,oil_consumption,other_renewable_consumption,primary_energy_consumption,renewables_consumption,solar_consumption,wind_consumption,year
country,,,,,,,,,,,,,,
China,337.917,361469.117,487737.471,24939.645,36363.133,50921.542,5722.187,101328.717,1594.944,538659.014,45199.355,1657.224,5246.143,42210
India,13.867,68108.280,115070.532,8771.234,5895.692,9493.848,1379.692,38191.021,704.672,124564.384,8114.152,334.294,1165.621,42210
Russia,0.000,22036.068,137378.463,82622.290,9059.757,17902.970,8809.805,32720.110,22.681,155281.435,9093.166,7.827,2.905,42210
United Kingdom,158.721,6900.709,42985.801,17746.279,264.667,6175.799,3792.566,18338.815,815.941,49161.600,2383.235,157.172,986.736,42210
United States,4934.899,106729.026,447216.452,134314.844,13941.447,73191.844,43569.838,206172.584,3963.672,520408.293,29622.003,1120.912,5661.075,42210

In [23]:
total_power_consumed.to_csv('Myenergy.csv') #save as csv